name: Package NuGet
on:
  push:
    branches:
      - main
jobs:
  build-test-analyze-package:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: '8.x'
      # Asegúrate de definir en los secrets los tokens para SonarCloud y GitHub Packages:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      NUGET_API_KEY: ${{ secrets.GH_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests with code coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage"
          ReportGenerator "-reports:**/coverage.cobertura.xml" "-targetdir:Cobertura" -reporttypes:MarkdownSummaryGithub

      - name: Begin SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        with:
          args: >
            begin
            /k:"$GITHUB_REPOSITORY"
            /d:sonar.login=${{ env.SONAR_TOKEN }}

      - name: Build solution
        run: dotnet build --no-restore

      - name: End SonarCloud analysis
        run: dotnet sonar end /d:sonar.login=${{ env.SONAR_TOKEN }}

      - name: Pack NuGet package from Bank.Domain
        run: dotnet pack ./Bank.Domain/Bank.Domain.csproj --configuration Release --output ./nupkg

      - name: Publish NuGet package to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg --source "github" --api-key ${{ env.GH_TOKEN }}
        env:
          NUGET_API_KEY: ${{ secrets.GH_TOKEN }}
